name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]

    env:
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PYTHONDONTWRITEBYTECODE: "1"
      QT_QPA_PLATFORM: "offscreen"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Ruff
        uses: astral-sh/ruff-action@v3.5.1
        with:
          args: "check --output-format=github ."

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov

      - name: Bandit
        continue-on-error: true
        run: |
          python -m pip install --upgrade pipx
          pipx run bandit -r . -x tests

      - name: Run pytests
        run: |
          xvfb-run -a pytest -q --maxfail=1 --disable-warnings --cov=./ --cov-report=term-missing
